# Generated by Django 5.2.9 on 2025-12-19 13:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userglobalstats",
            name="current_win_streak",
        ),
        migrations.RemoveField(
            model_name="userglobalstats",
            name="max_win_streak",
        ),
        migrations.RemoveField(
            model_name="userglobalstats",
            name="total_investment",
        ),
        migrations.RemoveField(
            model_name="userglobalstats",
            name="total_return",
        ),
        migrations.RemoveField(
            model_name="usersportstats",
            name="current_win_streak",
        ),
        migrations.RemoveField(
            model_name="usersportstats",
            name="max_win_streak",
        ),
        migrations.RemoveField(
            model_name="usersportstats",
            name="total_investment",
        ),
        migrations.RemoveField(
            model_name="usersportstats",
            name="total_return",
        ),
        migrations.AddField(
            model_name="userglobalstats",
            name="current_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userglobalstats",
            name="max_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userglobalstats",
            name="profile_halo_color",
            field=models.CharField(default="none", max_length=20),
        ),
        migrations.AddField(
            model_name="userglobalstats",
            name="reputation_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userglobalstats",
            name="units_returned",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=19
            ),
        ),
        migrations.AddField(
            model_name="usersportstats",
            name="current_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersportstats",
            name="max_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersportstats",
            name="units_returned",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=19
            ),
        ),
    ]
