# Generated by Django 5.2.10 on 2026-03-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_tipsterprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="User profile picture (max 5MB)",
                null=True,
                upload_to="avatars/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Short user biography (max 500 chars)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="tipsterprofile",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe Price ID for this tipster (created dynamically)",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="tipsterprofile",
            name="subscription_price",
            field=models.DecimalField(
                decimal_places=2,
                default=9.99,
                help_text="Monthly subscription price in EUR",
                max_digits=8,
            ),
        ),
    ]
