# Generated by Django 5.2.8 on 2025-12-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(blank=True, help_text='Final score for away team', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='External API identifier for this match', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(blank=True, help_text='Final score for home team', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
    ]
