# Generated by Django 5.2.8 on 2025-11-25 22:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('amount_gross', models.DecimalField(decimal_places=4, max_digits=19)),
                ('app_fee', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('amount_net', models.DecimalField(decimal_places=4, max_digits=19)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('SUBSCRIPTION', 'Subscription'), ('PAYOUT', 'Payout'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
