# Generated by Django 5.2.10 on 2026-01-29 01:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_stripeevent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="tipster",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="plan",
        ),
        migrations.DeleteModel(
            name="StripeEvent",
        ),
        migrations.RemoveField(
            model_name="stripeprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="subscriber",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="wallet",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="amount_gross",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="amount_net",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="app_fee",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="type",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="created",
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reference_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Dépôt"),
                    ("WITHDRAWAL", "Retrait"),
                    ("SUB_PAY", "Paiement Abonnement"),
                    ("COMMISSION", "Commission Tipster"),
                    ("BET_STAKE", "Mise Pari (Virtuel)"),
                    ("BET_WIN", "Gain Pari (Virtuel)"),
                ],
                default="DEPOSIT",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wallet",
            name="currency",
            field=models.CharField(default="EUR", max_length=3),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.DeleteModel(
            name="Plan",
        ),
        migrations.DeleteModel(
            name="StripeProfile",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
