name: "🚀 Feature / Issue"
description: "Nouvelle feature ou chantier technique"
labels: ["enhancement"]

body:
  - type: input
    id: blocked_by
    attributes:
      label: "Blocked by"
      description: "Si cette issue dépend d'une autre : Blocked by #<ID>"
      placeholder: "Blocked by #42"
    validations:
      required: false

  - type: textarea
    id: goal
    attributes:
      label: "Goal"
      description: "Ce que cette issue doit accomplir (1-3 phrases)"
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Liste des cases à cocher — Jules les utilisera pour valider"
      placeholder: |
        - [ ] Model X créé avec champs Y, Z
        - [ ] Endpoint POST /api/... retourne 201
        - [ ] python manage.py check passe
    validations:
      required: true

  - type: textarea
    id: migration
    attributes:
      label: "Migration"
      description: "Nom de la migration si applicable"
      placeholder: "N/A ou connect/migrations/0001_initial.py"
    validations:
      required: false

  - type: textarea
    id: dod
    attributes:
      label: "Definition of Done"
      value: |
        - [ ] Tous les AC sont satisfaits
        - [ ] `python manage.py check` passe
        - [ ] `python -m compileall apps/backend/src -q` passe
        - [ ] Le body de la PR contient `Closes #<numéro de cette issue>`
        - [ ] 1 migration maximum dans la PR (si applicable)
    validations:
      required: false
