# Generated by Django 5.2.10 on 2026-01-29 01:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BetTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("match_title", models.CharField(max_length=255)),
                ("selection", models.CharField(max_length=255)),
                ("odds", models.DecimalField(decimal_places=2, max_digits=5)),
                ("stake", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "ticket_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="tickets/%Y/%m/"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("WON", "Gagné"),
                            ("LOST", "Perdu"),
                            ("VOID", "Remboursé/Annulé"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "payout",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
