# Generated by Django 5.2.10 on 2026-03-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="betticket",
            name="settled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
