# Generated by Django 5.2.9 on 2025-12-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="betselection",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("WON", "Won"),
                    ("LOST", "Lost"),
                    ("VOID", "Void"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="betselection",
            name="stake",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="betselection",
            name="stats_processed",
            field=models.BooleanField(default=False),
        ),
    ]
