# Generated by Django 5.2.8 on 2025-12-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_enable_trigram_and_add_error_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='betselection',
            name='outcome',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void'), ('HALF_WON', 'Half Won'), ('HALF_LOST', 'Half Lost')], default='PENDING', max_length=20),
        ),
    ]
