# Generated by Django 5.2.10 on 2026-01-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_merge_20251219_1406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betselection",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("WON", "Won"),
                    ("LOST", "Lost"),
                    ("VOID", "Void"),
                    ("HALF_WON", "Half Won"),
                    ("HALF_LOST", "Half Lost"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
