# Generated by Django 5.2.8 on 2025-11-25 22:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='tickets/')),
                ('status', models.CharField(choices=[('PENDING_OCR', 'Pending OCR'), ('PROCESSING', 'Processing'), ('REVIEW_NEEDED', 'Review Needed'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected')], default='PENDING_OCR', max_length=20)),
                ('ocr_raw_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BetSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('selection', models.CharField(max_length=50)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_selections', to='sports.match')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='tickets.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
