# Generated by Django 5.2.9 on 2025-12-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_betselection_outcome_betselection_stake_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="betselection",
            name="kickoff_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
